#+title: xtramodifiers
#+email: giulio.pietroiusti@gmail.com
#+language: en
#+creator: Emacs 27.1 (Org mode 9.3)

xtramodifiers allows you to make normal keys behave like modifiers
(CTRL, ALT, etc.) when they are held down, but normally when pressed
and released. This can be extremely useful for those who, like Emacs'
users, make extensive use of modifiers.

keywords: dual function keys, extra modifiers, multi-purpose keys.

* Dependencies
xtramodifiers requires [[https://github.com/gvalkov/python-evdev][python-evdev]].

* Usage
You should first create a config file. In order to do so, you should
know the names xtramodifiers (like python-evdev) uses to refer to
keys.

Run
#+begin_src bash
python -m evdev.evtest
#+end_src

Choose the device (the keyboard whose behavior you want to modify).
You'll see the name of the keys as you press them.  Now you can create
a config file like the following (see config_example.py):
#+begin_src python
config = {
    'mod1': 'KEY_CAPSLOCK',
    'mod1_secondary_function': 'KEY_LEFTCTRL',
    'mod2': 'KEY_ENTER',
    'mod2_secondary_function': 'KEY_RIGHTCTRL',
    'max_delay': 0.3
}
#+end_src
A max_delay of 0.3 means that if you hold Enter (or whatever
``xtramodifier'' you have set up) down for more than 0.3 seconds and
don't hit any other key before releasing it, Enter is going to send no
input.

If you want only one xtramodifier, as opposed to two, then set mod2 to
None.

Now that you have a config file, you can start xtramodifiers with:
#+begin_src bash
sudo python xtramodifiers.py -c /path/to/config.py
#+end_src

If no path to a config file is given, then xtramodifiers looks for a
config.py file in the same directory.

By default, xtramodifiers shows you a list of device and asks you to
select one of them. If you don't want this interactive behaviour use
the '-d' option:

#+begin_src bash
sudo python xtramodifiers.py -c /path/to/config.py -d /dev/input/event3
#+end_src

* Similar Software
- [[https://github.com/mooz/xkeysnail/][xkeysnail]]

- [[https://gitlab.com/interception/linux/plugins/dual-function-keys][interception dual function keys]]

- [[https://gitlab.com/at-home-modifier/at-home-modifier-evdev][at home modifier]]

* Bugs
- touchpad stops working --- whereas buttons and trackpoint work.

- xtramodifiers, when executed, resets my xkb configuration, so I have
  to restore it each time.

* License
xtramodifiers

Copyright (C) 2020  Giulio Pietroiusti

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
